### ISSUE TITLE
Unable to use global transforms.

### ISSUE THREAD

**Issue by DylanPiercey** [ngryman/gulp-bro#17]
Currently the only way I can find to use global transforms is programatically, before bundling. As such it is impossible to use them with bro.

```js
var bundler = browserify(__dirname + '/index.js')
bundler.transform({ global: true }, 'uglifyify')
```

**Comment by ngryman** [comment]
Hi,

It's possible 😎

```javascript
bro({
  transform: [[uglifyify(), { global: true }]
})
```

Ref: https://github.com/substack/node-browserify/issues/1267#issuecomment-102798921.

**Comment by DylanPiercey** [comment]
@ngryman awesome! And thanks for adding the example.
