### ISSUE TITLE
browserify and watchify as peer dependencies

### ISSUE THREAD

**Issue by niksy** [ngryman/gulp-bro#2]
Would it make sense to make browserify and watchify peer dependencies? Right now, they are defined as hard dependencies of this plugin, but maybe project consuming it uses different version of those tools (e.g. you’re on `^13.0.0` for browserify, but your project, for whatever reason, uses `^10.0.0`).

**Comment by ngryman** [comment]
Peer dependencies are deprecated: https://github.com/npm/npm/issues/6565.
The vast majority of users shouldn't need to have a dependency on `browserify`/`watchify`, that's the whole point :)

But I hear you, it could happen. `npm` dedupes by default now, so I can probably lower dependencies versions and use `>=` to make sure `gulp-bro` will use the version installed by the user.

**Comment by niksy** [comment]
I’m sorry, I didn’t mean explicit `peerDependencies` (I’m familiar with deprecation), just that user should install `gulp-bro` with:

```sh
npm install gulp-bro browserify watchify
```

Similar to how you install e.g. ESLint plugins and rules - ESLint doesn’t get installed implicitly, or just about any other Gulp plugin.

**Comment by ngryman** [comment]
I get you. But as I explained above, the vast majority of users won't need `browserify`/`watchify` explicitly. `gulp-bro` is here to wrap them, not *enhance* them.

The relationship between `eslint`, its plugins and the user is totally different from here.

**Comment by niksy** [comment]
Ah, OK. :)
