### ISSUE TITLE
Support for multiple bundles

### ISSUE THREAD

**Issue by XuluWarrior** [ngryman/gulp-bro#25]
I want to be able to split my source into multiple bundles as per https://github.com/substack/node-browserify#multiple-bundles

I am currently splitting into a 3rd party bundle and my source.  Calling browserify on the 3rd part code and then gulp-bro on my code.  This makes the incremental building a lot quicker.

This relies on being able to set the external flag which doesn't seem possible with the current configuration options as the Opt object doesn't include externals.

Please correct me if I'm wrong and there's a way to do this that I've missed.

**Comment by ngryman** [comment]
Hey, have you tried to set `bundleExternal` to `false` in order to exclude all 3rd party modules from your bundle?

**Comment by XuluWarrior** [comment]
I saw this flag but I don't know how to use this boolean setting to tell browserify which modules are 3rd party modules.  I have only managed this by using the -external argument.

**Comment by ngryman** [comment]
I don't really know either... 😞
You could probably use this flag with `gulp-bro` and find a manner to only bundle external deps with `browserify`. I would suggest some research on the subject.

Concerning `gulp-bro`, I'm closing this issue as I'm forwarding all options to `browserify`, there is nothing more I can do. We can continue to discuss on the subject if you want to.

**Comment by XuluWarrior** [comment]
I don't think I've explained myself very well.

I know one way to to do what I want but it involves calling a method on the browserify object itself rather than providing the information in the options object.

My commit to my branch, https://github.com/XuluWarrior/gulp-bro/commit/87efc4bdd1cd2ba072207b915ebccfda761cad2d, shows how I've hacked gulp-bro to allow the method call.

**Comment by ngryman** [comment]
Ok I understand now. What I don't, is that `external` option seems to be supported: https://github.com/substack/node-browserify/blob/master/index.js#L182. I would just like to understand if calling `#external` is really necessary. If so I'll add support for it.

**Comment by XuluWarrior** [comment]
The line you refer to is in the *require* method.  When gulp-pro creates the browserify object this method is invoked by *add* at https://github.com/substack/node-browserify/blob/master/index.js#L92

As you can see *opts* is not the same as *self.opts*

**Comment by ngryman** [comment]
Ok so I guess we have no other choice than calling `#external` like you did.
I would also like to add a recipe for multiple bundle in the `readme`. Would you mind giving me an example on how you do it?
Thanks!

**Comment by ngryman** [comment]
Released as `0.3.2`.
