### ISSUE TITLE
Rollup support

### ISSUE THREAD

**Issue by TesseractG** [ngryman/gulp-bro#28]
First of all; I love this plugin! I have replaced most of my browserify and source stream stuff to this and it works well.

I just have a feature request. Would it be possible to also support Rollup? Rollup-stream (https://github.com/Permutatrix/rollup-stream) is pretty much a drop-in replacement for Browserify. I think it would be nice if people can pick the backend they want and I personally believe that Rollup has a couple of advantages of Browserify.

If this is something worth pursuing for you, I also would not mind working on implementing it.

**Comment by ngryman** [comment]
Hi and thanks for your comment!

I know `rollup` very well and use it in most of my projects now 🎉 .
Still, `gulp-bro` is about doing one thing:
> gulp + browserify + incremental build

There are a number of differences between `rollup` and `browserify` that prevents me to consider it as a *backend* for `gulp-bro`.
Furthermore, people either use `browserify` or `rollup`. Supporting both in the same project seems to be a lost of focus to me.

However I would be open to create a separate related project to support `rollup`. But it seems that other `gulp` plugins already exist though. Why aren't they satisfying you at the moment?

**Comment by TesseractG** [comment]
Thanks for the quick follow-up 👍 

You are correct, of course, if this were to happen it should probably be a separate project...

The reason I like gulp-bro over manually setting up a browserify gulp task chain is exactly that; it is one thing that works out of the box. Even using rollup-stream (which works very well!), one still needs vinyl-source-stream and cache handling is _weird_. I have this up and running for some projects and am quite happy with it, I just figured that there is room for a more "out-of-the-box" solution a la gulp-bro, which rollup-stream does not yet satisfy.

**Comment by ngryman** [comment]
Isn't [gulp-rollup](https://github.com/mcasimir/gulp-rollup) good enough?

There are also:
- https://github.com/MikeKovarik/gulp-better-rollup
- https://github.com/bedeoverend/gulp-rollup-file
- https://github.com/renanhangai/gulp-rollup-stream

**Comment by TesseractG** [comment]
I never really touched gulp-rollup, because of the warning at the top;

> Note: This plugin is not appropriate for most use cases, as it requires every file expected to be imported by Rollup to be loaded into memory preemptively. rollup-stream is preferred for almost all purposes.

So I looked at rollup-stream with gulp and it is not nearly as convenient as gulp-bro to use.

I have to admit I never looked much beyond those 2 options and gulp-better-rollup already seems to be a potential winner. I just went straight here... I suppose I should have looked around a bit better.

Thanks a lot for the tips and sorry for creating a useless issue!

**Comment by ngryman** [comment]
No problem! Closing this for now. Tell me if `gulp-better-rollup` fits your needs.

**Comment by TesseractG** [comment]
gulp-better-rollup indeed seems to do what I want, as long as I combine it with the right plugins. Got my pipeline working fine now! Thanks again for the suggestion.

**Comment by ngryman** [comment]
You're welcome.
