### ISSUE TITLE
Remove gulp-util (deprecated)

### ISSUE THREAD

**Issue by ba55ie** [ngryman/gulp-bro#44]
With the release of gulp 4.0.0 `gulp-util` has been deprecated.

https://github.com/gulpjs/gulp-util

**Comment by ngryman** [comment]
I've upgraded dependencies and replace `gulp-util`. Would you mind testing `master` and if it works correctly for you? If so, I'll make a new release. Thansk!

**Comment by ba55ie** [comment]
Hi, thanks for the update. Everything seems to be working just fine. 💯

**Comment by ngryman** [comment]
Released 🎉 
Thanks for the help!
