### ISSUE TITLE
ParseError: Unexpected token

### ISSUE THREAD

**Issue by semiromid** [ngryman/gulp-bro#56]
Thank you for this plugin! But is problem.

If import css style not from folder "node_modules" --- it will be work!

If import css style from folder "node_modules" --- it will not be work :(

> [13:35:36] Finished 'eslint.js' after 189 ms
> [13:35:36] [bro] SyntaxError

>  ...\app_js\node_modules\cropperjs\dist\AppRoot.css:1
>  .button__GI_m1{padding:8px 12px;}

I use `browserify-postcss`
https://github.com/zoubin/browserify-postcss/

**Comment by ngryman** [comment]
Hey @semiromid ,

Sorry for the late answer here. I suspect it might come from a configuration issue with paths. It's been one year, but just in case I would suggest that you take a look at `browserify` and `browserify-postcss` configuration options to fix the issue.

I'll close the issue as it's not related to `gulp-bro`.
