### ISSUE TITLE
React and jsx scripts not getting compiled on windows 10

### ISSUE THREAD

**Issue by KenEucker** [ngryman/gulp-bro#57]
I switched to this package today over gulp-browserify after discovering that gulp-browserify is no longer being maintained. On Mac OS I can build my jsx and it makes it into the output where I expect it. However, on Windows 10 it does not include anything but the following javascript:

`(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({},{},[]);`

If I switch back to gulp-browserify on Windows 10, it works just fine. So I think this issue is with gulp-bro, but I need to investigate further to determine what the cause of the issue is.

Has anyone else had any issues running gulp-bro on Windows?

**Comment by KenEucker** [comment]
Checking back in on this to say that I think I misunderstood my situation. I'm seeing my js compiled to the code in the original post after moving from gulp-browserify to gulp-bro on all machines. So this isn't a windows issue, but an issue with gulp-browserify ( or the options I'm sending it ). I'll investigate when I've got the time.

Does anyone happen to have a "migrate from gulp-browserify to gulp-bro" article that I could be pointed to?

**Comment by ngryman** [comment]
Hey @KenEucker ,

Sorry for the late answer. At first glance I also don't think it would come from a platform difference (Win 10 vs OS X). It looks like a module couldn't be found. Could it be an issue with an dependency that was not installed for example?

I'll default to close the issue as it's old and I suspect it's not related to `gulp-bro`. Feel free to re-open it if you isolated a bug!
