### ISSUE TITLE
Remove bro build time log (toggle).

### ISSUE THREAD

**Issue by DylanPiercey** [ngryman/gulp-bro#6]
Would be nice if the logging here could be configurable since gulp already logs the time taken.
<img width="325" alt="screen shot 2016-05-13 at 10 40 25 pm" src="https://cloud.githubusercontent.com/assets/4985201/15266243/fc9cd228-195b-11e6-9587-bd47a5a04429.png">

Otherwise this module is awesome, always happy to delete a chunk of my own code / consolidate deps and the standard browserify-incremental setup is pretty clunky.

**Comment by ngryman** [comment]
Hey,

Sure, seems legit, will plan it for the next release.

**Comment by DylanPiercey** [comment]
Thanks for merging the fix!
