### ISSUE TITLE
Creating a bundle using multiple entry files

### ISSUE THREAD

**Issue by LeeKevin** [ngryman/gulp-bro#64]
My original build looked like 

       let props = {
            entries: ['one.js', 'two.js'],
            transforms: [...]
        }
       let bundler = browserify(props)
            .bundle()
            .pipe(source(name + '.js'))
            .pipe(buffer())
            ...

How can I do something similar with gulp-bro?

- Bundle multiple entry files
- Create a new stream with different name using the resulting bundle

**Comment by ecDusty** [comment]
@LeeKevin I'm not sure 100% sure what you're needing to do. But with my dev builds I have a main JS folder that has the JS files, which load other component files. Then these main js files are outputted to my DIST folder.

Example of main.js:
```
/**
 * Imported features
 */

// Lazyload (npm install lazysizes)
import 'lazysizes';

// Swiper (npm install swiper)
// import 'swiper';

/**
 * Build Components
 */
import '../components/header/_header';
import '../components/forms/forms';
```

You can see that this pulls in other files. Which then run together. Should I required to pull functions or objects from the component files, then I'd need to make use of import to variable and Export within the component files.

You can see this in action on a current project i'm working on.
https://github.com/ecDusty/Udacity-FEND-Projects/tree/master/Project%201%20-%20Personal%20Blog%20Website
